#!/usr/bin/env bash

# This script configures the Nginx server so that

# /redirect_me is redirecting to another page


sudo apt-get -y update

sudo apt-get -y install nginx

sudo chown -R "$USER":"$USER" /var/www

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo mkdir -p /var/www/error

echo "Ceci n'est pas une page" | sudo tee /var/www/error/404.html

printf %s "server {

    listen 80;

    listen [::]:80 default_server;

    root   /etc/nginx/html;

    index  index.html index.htm;

    location /redirect_me {

        return 301 http://cuberule.com/;

    }

    error_page 404 /404.html;

    location /404 {

      root /etc/nginx/html;

      internal;

    }

}" > /etc/nginx/sites-available/default


service nginx restart
